/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.sotugyouseisaku.app;
 
 
 
public class AppTest {
     public void appHasAGreeting() {
        App classUnderTest = new App();
       
    }
}
