server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://sotugyouseisaku-postgres:5432/sotugyouseisaku_db
    username: root
    password: root
  sql:
    init:
      mode: always             # SQL初期化を常に実行
      continue-on-error: false # エラーがあれば起動を中止する
      schema-locations:
        - classpath:schema/01_car_navigation.sql
        - classpath:schema/02_drive_recorder.sql
        - classpath:schema/03_smartphone_holder.sql
        - classpath:schema/04_product_view.sql
        # - classpath:schema/05_cart.sql
      data-locations:
        - classpath:data/01_car_navigation.sql
        - classpath:data/02_drive_recorder.sql
        - classpath:data/03_smartphone_holder.sql

logging:
  level:
    org.springframework.jdbc.datasource.init.ScriptUtils: DEBUG # SQL読み込みの詳細ログ

mybatis:
  config-location: classpath:mybatis-config.xml