server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://serious-postgres:5432/sotugyouseisaku_db
    username: root
    password: root
  sql:
    init:
      mode: always             # SQL初期化を常に実行
      continue-on-error: false # エラーがあれば起動を中止する

logging:
  level:
    org.springframework.jdbc.datasource.init.ScriptUtils: DEBUG # SQL読み込みの詳細ログ